### PR TITLE
Issue/48/circe support

### PR DESCRIPTION
**Pull request by emanresusername**
addresses #48 @zmeda

### CODE REVIEW

**Comment by aroberts** [comment]
Any motion on this? I am interested in checking out this project, but as a circe user, I am waiting for this PR to make it into a release.

**Comment by emanresusername** [comment]
in the mean time, would people be interested in a generic model marshallers type class similar to the generic `RootObjectReaders` and `RootObjectWriters` ?

**Comment by zmeda** [comment]
New version released (v0.4.2) on sonatype.

**Comment by emanresusername** [comment]
@zmeda

**Comment by emanresusername** [comment]
@aroberts

**Pull request merged**
